[package]
name = "cellular"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
clearscreen = "4.0.2"
colored = "3.0.0"
rand = "0.9.2"
rayon = "1.11.0"
image = "0.25.9"
webp-animation = "0.9.0"
clap = { version = "4.5.53", features = ["derive"] }
